### ISSUE TITLE
Zero Touch deployment

### ISSUE THREAD

**Issue by vandamj** [FreeTAKTeam/FreeTAKServer-User-Docs#72]
Hi there 
Thank you making this available for free.
I have one issue.
I ran the Zero Touch deployment and all went well.
When I try login using the default admin and password . the system comes up with txt ans says connection refused.
[Connection refused.docx](https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/files/15157184/Connection.refused.docx)

**Comment by phreed** [comment]
This has be corrected, in part in version 2.2.1.
Here is how the error is presented in v2.2.1
![image](https://github.com/FreeTAKTeam/FreeTAKServer-User-Docs/assets/211644/ce683030-c859-4eaa-a9e9-3b6c7b5cab29)

The problem with this message is that it does not help you to know what to do.
Here are some options:
* https://babeloff.github.io/FreeTAKServer-User-Docs/Installation/mechanism/Ansible/ZeroTouchInstall/#explicit-ip-address
* https://babeloff.github.io/FreeTAKServer-User-Docs/administration/Operation/fts-config/
* https://babeloff.github.io/FreeTAKServer-User-Docs/About/FAQ/

The problem is that a step was missed during the installation.
Probably not supplying an appropriate IP address.
I am thinking we add an entry to the FAQ, matching the message "FTS Server is Not Reachable At x.x.x.x" and providing the previous explanation and the links to correcting the configuration. 
Would that be sufficient?

@naman108
